import json
import re
import urllib.request
import urllib.error
import ssl
import time

# Plugin data to fetch - (vstFileName, url_slug, brand)
plugins_to_fetch = [
    ('AMEK EQ 250', 'amek_eq_250', 'AMEK'),
    ('Ampeg SVTVR Classic', 'ampeg_svtvr_classic', 'Ampeg'),
    ('Arousor', 'spl_arousor', 'SPL'),
    ('Arousor Lt', 'spl_arousor_lt', 'SPL'),
    ('Bettermaker BM60', 'bettermaker_bm60', 'Bettermaker'),
    ('Bettermaker Bus Compressor', 'bettermaker_bus_compressor', 'Bettermaker'),
    ('Bettermaker Bus Compressor DSP', 'bettermaker_bus_compressor', 'Bettermaker'),  # Same page
    ('Bettermaker C502V DSP', 'bettermaker_c502v', 'Bettermaker'),
    ('Bettermaker Mastering Compressor DSP', 'bettermaker_mastering_compressor', 'Bettermaker'),
    ('Bettermaker Passive Equalizer', 'bettermaker_peq1', 'Bettermaker'),
    ('Dangerous BAX EQ Master', 'dangerous_bax_eq', 'Dangerous Music'),
    ('ENGL E765 RT', 'engl_e765_rt', 'ENGL'),
    ('Friedman BE100', 'friedman_be100', 'Friedman'),
    ('Fuchs Train II', 'fuchs_train_ii', 'Fuchs Audio'),
    ('Kiive Tape Face', 'kiive_tape_face', 'Kiive Audio'),
    ('Kiive Xtressor', 'kiive_xtressor', 'Kiive Audio'),
    ('Knif Audio Knifonium', 'knif_knifonium', 'Knif Audio'),
    ('Lindell 354E', 'lindell_354e', 'Lindell Audio'),
    ('Lindell 50 Buss', 'lindell_50_series', 'Lindell Audio'),
    ('Lindell 50 Channel', 'lindell_50_series', 'Lindell Audio'),
    ('Lindell 69 Buss', 'lindell_69_series', 'Lindell Audio'),
    ('Lindell 69 Channel', 'lindell_69_series', 'Lindell Audio'),
    ('Lindell 80 Bus', 'lindell_80_series', 'Lindell Audio'),
    ('Lindell 80 Channel', 'lindell_80_series', 'Lindell Audio'),
    ('Lindell 902 De-esser', 'lindell_902_de-esser', 'Lindell Audio'),
    ('Lindell ChannelX', 'lindell_channelx', 'Lindell Audio'),
    ('Lindell MBC', 'lindell_mbc', 'Lindell Audio'),
    ('Lindell MU-66', 'lindell_mu-66', 'Lindell Audio'),
    ('Lindell SBC', 'lindell_sbc', 'Lindell Audio'),
    ('Lindell TE-100', 'lindell_te-100', 'Lindell Audio'),
    ('Looptrotter SA2RATE2', 'looptrotter_sa2rate_2', 'Looptrotter'),
    ('Maag EQ2', 'maag_eq2', 'Maag Audio'),
    ('Maag MAGNUM-K', 'maag_magnum-k', 'Maag Audio'),
    ('Millennia TCL-2', 'millennia_tcl-2', 'Millennia'),
    ('NEOLD OLDTIMER', 'neold_oldtimer', 'NEOLD'),
    ('NEOLD WUNDERLICH', 'neold_wunderlich', 'NEOLD'),
    ('SPL De-Esser', 'spl_de-esser', 'SPL'),
    ('SPL De-Esser Dual-Band', 'spl_de-esser_dual-band', 'SPL'),
    ('SPL Passeq Single', 'spl_passeq', 'SPL'),
    ('Schoeps Mono Upmix 1to2', 'schoeps_mono_upmix', 'Schoeps'),
    ('Shadow Hills Class A Mastering Comp', 'shadow_hills_class_a_mastering_comp', 'Shadow Hills'),
    ('TBTECH Kirchhoff-EQ', 'tbt_kirchhoff-eq', 'Three-Body Technology'),
    ('TBTECH Trinity Shaper', 'tbt_trinity_shaper', 'Three-Body Technology'),
    ('Unfiltered Audio Bass Mint', 'unfiltered_audio_bass_mint', 'Unfiltered Audio'),
    ('Unfiltered Audio Dent 2', 'unfiltered_audio_dent_2', 'Unfiltered Audio'),
    ('bx_2098 EQ', 'bx_2098_eq', 'Brainworx'),
    ('bx_blackdist2', 'bx_blackdist2', 'Brainworx'),
    ('bx_bluechorus2', 'bx_bluechorus2', 'Brainworx'),
    ('bx_boom', 'bx_boom', 'Brainworx'),
    ('bx_boom V3', 'bx_boom', 'Brainworx'),
    ('bx_cleansweep Pro', 'bx_cleansweep_pro', 'Brainworx'),
    ('bx_cleansweep V2', 'bx_cleansweep_v2', 'Brainworx'),
    ('bx_clipper', 'bx_clipper', 'Brainworx'),
    ('bx_console AMEK 200', 'bx_console_amek_200', 'Brainworx'),
    ('bx_console AMEK 9099', 'bx_console_amek_9099', 'Brainworx'),
    ('bx_control V2', 'bx_control_v2', 'Brainworx'),
    ('bx_crispyscale', 'bx_crispytuner', 'Brainworx'),
    ('bx_crispytuner', 'bx_crispytuner', 'Brainworx'),
    ('bx_digital V3 mix', 'bx_digital_v3', 'Brainworx'),
    ('bx_dynEQ V2 Mono', 'bx_dyneq_v2', 'Brainworx'),
    ('bx_enhancer', 'bx_enhancer', 'Brainworx'),
    ('bx_glue', 'bx_glue', 'Brainworx'),
    ('bx_hybrid V2 mix', 'bx_hybrid_v2', 'Brainworx'),
    ('bx_limiter', 'bx_limiter', 'Brainworx'),
    ('bx_masterdesk True Peak', 'bx_masterdesk', 'Brainworx'),
    ('bx_megadual', 'bx_megadual', 'Brainworx'),
    ('bx_megasingle', 'bx_megasingle', 'Brainworx'),
    ('bx_metal2', 'bx_metal2', 'Brainworx'),
    ('bx_oberhausen', 'bx_oberhausen', 'Brainworx'),
    ('bx_rockergain100', 'bx_rockergain100', 'Brainworx'),
    ('bx_rockrack V3 Player', 'bx_rockrack_v3', 'Brainworx'),
    ('bx_rooMS', 'bx_rooms', 'Brainworx'),
    ('bx_solo', 'bx_solo', 'Brainworx'),
    ('bx_stereomaker', 'bx_stereomaker', 'Brainworx'),
    ('bx_tonebox', 'bx_tonebox', 'Brainworx'),
    ('bx_yellowdrive', 'bx_yellowdrive', 'Brainworx'),
    ('elysia alpha master', 'elysia_alpha_compressor', 'elysia'),
    ('elysia alpha mix', 'elysia_alpha_compressor', 'elysia'),
    ('elysia karacter master', 'elysia_karacter', 'elysia'),
    ('elysia karacter mix', 'elysia_karacter', 'elysia'),
    ('elysia museq master', 'elysia_museq', 'elysia'),
    ('elysia nvelope', 'elysia_nvelope', 'elysia'),
    ('elysia phils cascade', 'elysia_phil_s_cascade', 'elysia'),
    ('fiedler audio spacelab beam', 'fiedler_audio_spacelab_ignition', 'fiedler audio'),
    ('fiedler audio spacelab ignition', 'fiedler_audio_spacelab_ignition', 'fiedler audio'),
    ('fiedler audio splat', 'fiedler_audio_splat', 'fiedler audio'),
]

# Descriptions to add manually (since web scraping is complex)
manual_descriptions = {
    'AMEK EQ 250': 'Vintage parametric EQ with warm analog character.',
    'Ampeg SVTVR Classic': 'Classic version of the legendary SVT-VR all-tube bass amp.',
    'Arousor': 'Transient designer and compressor with unique parallel compression.',
    'Arousor Lt': 'Streamlined version of the Arousor transient designer.',
    'Bettermaker BM60': 'Analog-modeled 60-band mastering EQ with precision control.',
    'Bettermaker Bus Compressor': 'VCA bus compressor for gluing mixes with punch and clarity.',
    'Bettermaker Bus Compressor DSP': 'Hardware-connected version of the Bettermaker Bus Compressor.',
    'Bettermaker C502V DSP': 'Hardware-connected 500-series VCA compressor.',
    'Bettermaker Mastering Compressor DSP': 'Hardware-connected mastering compressor with analog warmth.',
    'Bettermaker Passive Equalizer': 'Passive mastering EQ with Pultec-style curves.',
    'Dangerous BAX EQ Master': 'Mastering version of the Baxandall-style tone control EQ.',
    'ENGL E765 RT': 'Retro Tube amp with vintage EL34 tone and modern features.',
    'Friedman BE100': 'Boutique high-gain amp inspired by hot-rodded British designs.',
    'Fuchs Train II': 'Tweed-inspired amp with Train Wreck-style overdrive.',
    'Kiive Tape Face': 'Tape saturation processor with vintage warmth.',
    'Kiive Xtressor': 'Aggressive FET compressor with character.',
    'Knif Audio Knifonium': 'Monophonic tube synthesizer with unique analog sound.',
    'Lindell 354E': 'Neve 2254-style diode bridge compressor.',
    'Lindell 50 Buss': 'API 2500-style bus compressor.',
    'Lindell 50 Channel': 'API-style channel strip with EQ and dynamics.',
    'Lindell 69 Buss': 'Helios-style bus compressor.',
    'Lindell 69 Channel': 'Helios-style channel strip.',
    'Lindell 80 Bus': 'Neve 80-series bus compressor.',
    'Lindell 80 Channel': 'Neve 80-series channel strip.',
    'Lindell 902 De-esser': 'Precision de-esser for vocal processing.',
    'Lindell ChannelX': 'Versatile channel strip combining multiple vintage circuits.',
    'Lindell MBC': 'Multi-band compressor for mastering and mixing.',
    'Lindell MU-66': 'Fairchild 660/670-style tube limiter.',
    'Lindell SBC': 'SSL-style bus compressor.',
    'Lindell TE-100': 'Tube saturation and enhancement processor.',
    'Looptrotter SA2RATE2': 'Dual-channel tube and transformer saturation.',
    'Maag EQ2': 'Two-band EQ with the legendary Air Band.',
    'Maag MAGNUM-K': 'Compressor with unique Air Band limiting.',
    'Millennia TCL-2': 'Twin Com tube compressor/limiter for mastering.',
    'NEOLD OLDTIMER': 'Vintage tape delay emulation with modulation.',
    'NEOLD WUNDERLICH': 'Tube saturator modeled from rare German broadcast gear.',
    'SPL De-Esser': 'Precision de-esser for removing sibilance.',
    'SPL De-Esser Dual-Band': 'Two-band de-esser for precise sibilance control.',
    'SPL Passeq Single': 'Single-channel version of the passive mastering EQ.',
    'Schoeps Mono Upmix 1to2': 'Convert mono to stereo with natural spatial imaging.',
    'Shadow Hills Class A Mastering Comp': 'Class A discrete version of the mastering compressor.',
    'TBTECH Kirchhoff-EQ': '32-band parametric EQ with analog modeling and dynamics.',
    'TBTECH Trinity Shaper': 'Multi-mode transient shaper with advanced control.',
    'Unfiltered Audio Bass Mint': 'Bass enhancement and sub synthesis.',
    'Unfiltered Audio Dent 2': 'Waveform manipulation with clipping and modulation.',
    'bx_2098 EQ': 'Amek 9098-style parametric EQ with TMT modeling.',
    'bx_blackdist2': 'ProCo RAT-style distortion pedal.',
    'bx_bluechorus2': 'Boss CE-2 style chorus with stereo enhancement.',
    'bx_boom': 'Low-end enhancement and sub-bass processor.',
    'bx_boom V3': 'Enhanced bass processor with additional controls.',
    'bx_cleansweep Pro': 'High and low-pass filter for cleaning mixes.',
    'bx_cleansweep V2': 'Precision filter for removing unwanted frequencies.',
    'bx_clipper': 'Clipping saturator for loudness and harmonics.',
    'bx_console AMEK 200': 'AMEK 200 console channel strip with TMT modeling.',
    'bx_console AMEK 9099': 'AMEK 9099 console channel strip with TMT modeling.',
    'bx_control V2': 'Monitor controller and metering suite.',
    'bx_crispyscale': 'Guitar and bass tuner with scale detection.',
    'bx_crispytuner': 'Real-time vocal pitch correction.',
    'bx_digital V3 mix': 'M/S mastering EQ optimized for mixing.',
    'bx_dynEQ V2 Mono': 'Mono version of the dynamic EQ.',
    'bx_enhancer': 'Harmonic enhancement for adding presence.',
    'bx_glue': 'Mix bus processor for cohesive sound.',
    'bx_hybrid V2 mix': 'M/S EQ optimized for mixing applications.',
    'bx_limiter': 'Transparent brickwall limiter.',
    'bx_masterdesk True Peak': 'One-knob mastering with true peak limiting.',
    'bx_megadual': 'Dual-rectifier style high-gain amp.',
    'bx_megasingle': 'Single-channel high-gain amp.',
    'bx_metal2': 'Modern metal amp for aggressive tones.',
    'bx_oberhausen': 'Analog-style synthesizer with classic waveforms.',
    'bx_rockergain100': 'High-gain rock amp with Marshall-style tone.',
    'bx_rockrack V3 Player': 'Preset player for the bx_rockrack amp suite.',
    'bx_rooMS': 'Room simulation and ambience processor.',
    'bx_solo': 'Mid-side solo and mute utility.',
    'bx_stereomaker': 'Mono to stereo converter with width control.',
    'bx_tonebox': 'Guitar tone shaping with amp-style EQ.',
    'bx_yellowdrive': 'Boss OD-1 style overdrive pedal.',
    'elysia alpha master': 'Mastering version of the alpha compressor.',
    'elysia alpha mix': 'Mix version of the alpha compressor.',
    'elysia karacter master': 'Mastering saturator with parallel compression.',
    'elysia karacter mix': 'Mix version of the karacter saturator.',
    'elysia museq master': 'Mastering version of the museq EQ.',
    'elysia nvelope': 'Transient designer for attack and sustain control.',
    'elysia phils cascade': 'Cascading compressor with unique character.',
    'fiedler audio spacelab beam': 'Spatial audio beam forming tool.',
    'fiedler audio spacelab ignition': 'Immersive audio reverb and spatial processor.',
    'fiedler audio splat': 'Transient shaper for spatial audio.',
}

# Load JSON
with open('C:/Users/charl/PluginAllianceLauncher/plugins.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

# Update plugins with manual descriptions
updated = 0
for plugin in data['plugins']:
    vst_name = plugin['vstFileName']
    if vst_name in manual_descriptions and not plugin.get('description'):
        plugin['description'] = manual_descriptions[vst_name]
        updated += 1
        print(f"Updated description for: {vst_name}")

# Save
with open('C:/Users/charl/PluginAllianceLauncher/plugins.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print(f"\nUpdated {updated} plugins with descriptions.")
